### ISSUE TITLE
Host the jupyter tab as a  standalone page

### ISSUE THREAD

**Issue by stratosgear** [CS-SI/eodag-labextension#116]
Is it possible to host the search page (the left tab on Jupyter) as a standalone web page?

Or is it too tightly integrated into some Jupyter functionality?

In other words, how much work is it to make this eodag "gui" work without Jupyter?  Any hints?

Thanks!

**Comment by sbrunato** [comment]
hello @stratosgear , making this work without jupyterlab would be part of another project. This has been written as a jupyterlab extension and will not work without jupyter.

**Comment by stratosgear** [comment]
Thanks Sylvain.

> making this work without jupyterlab would be part of another project. 

Trying to parse your comment...

Do you imply that this is part of another ongoing "coming-soon" project, or that it "**should**" be part of a completely separate project?

**Comment by stratosgear** [comment]
In any case, I guess this can be closed, as it is not a real issue. Thanks Again!

**Comment by sbrunato** [comment]
> Do you imply that this is part of another ongoing "coming-soon" project, or that it "should" be part of a completely separate project?

A portal like https://hydroweb.next.theia-land.fr/ can already generate an `eodag` download script from its GUI. You can also `eodag` in [server mode with STAC Browser](https://eodag.readthedocs.io/en/stable/stac_rest.html#browsing), this will not generate Python code but will use eodag to search and download in the backend of STAC browser
